version: '3.8'
services:
  web:
    container_name: dolphin-admin-react-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    env_file:
      - .env.development
